// <auto-generated />
using AV_Soft.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AV_Soft.Migrations
{
    [DbContext(typeof(AVSContext))]
    partial class AVSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AV_Soft.Model.Tab1", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KEY")
                        .HasColumnType("int");

                    b.Property<int>("VALUE")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Tab1");
                });

            modelBuilder.Entity("AV_Soft.Model.Tab2", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("COUNT")
                        .HasColumnType("int");

                    b.Property<int>("COUNTMORETHENONE")
                        .HasColumnType("int");

                    b.Property<int>("KEY")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Tab2");
                });
#pragma warning restore 612, 618
        }
    }
}
